/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<number>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: number;
}

export interface Articles {
  category_id: number | null;
  date_created: Generated<Timestamp>;
  date_written: Timestamp | null;
  id: Generated<number>;
  relevance_score: number | null;
  source: string | null;
  summary: string | null;
  text: string;
  vector: string | null;
}

export interface Categories {
  date_created: Generated<Timestamp>;
  icon: string | null;
  id: Generated<number>;
  name: string;
}

export interface Feedback {
  article_id: number;
  date_created: Generated<Timestamp>;
  id: Generated<number>;
  score: number;
  text: string | null;
  user_id: number;
}

export interface Podcasts {
  date_created: Generated<Timestamp>;
  id: Generated<number>;
  s3_link: string | null;
  script: string;
  spotify_link: string | null;
  user_id: number | null;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<number>;
  sessionToken: string;
  userId: number;
}

export interface Settings {
  category_ids: Generated<number[]>;
  created_at: Generated<Timestamp>;
  delivery_method: Generated<string | null>;
  frequency: Generated<string | null>;
  id: Generated<number>;
  language: string | null;
  length: Generated<number | null>;
  preference_vector: string | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Users {
  email: string | null;
  emailVerified: Timestamp | null;
  id: Generated<number>;
  image: string | null;
  name: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  accounts: Accounts;
  articles: Articles;
  categories: Categories;
  feedback: Feedback;
  podcasts: Podcasts;
  sessions: Sessions;
  settings: Settings;
  users: Users;
  verification_token: VerificationToken;
}
